### ISSUE TITLE
Git message does not match for newer versions

### ISSUE THREAD

**Issue by fastjames** [jordanbyron/capistrano_confirm_branch#4]
https://github.com/jordanbyron/capistrano_confirm_branch/blob/6e895ad670014cf9f5baab5efe9757f4fd4dede0/lib/capistrano/tasks/confirm_branch.rake#L42

The message from my (recent) version of git reads
```
Your branch is up to date with 'origin/master'.
```
I think changing the dashes to dots would be flexible enough to accomodate both message formats.

**Comment by jordanbyron** [comment]
@fastjames it checks out

```ruby
old_status = "Your branch is up-to-date with 'origin/master'"
# => "Your branch is up-to-date with 'origin/master'"
new_status = "Your branch is up to date with 'origin/master'"
#=> "Your branch is up to date with 'origin/master'"
old_status[/Your branch is up.to.date/]
# => "Your branch is up-to-date"
new_status[/Your branch is up.to.date/]
#=> "Your branch is up to date"
"Your branch is LOL"[/Your branch is up.to.date/]
# => nil
```

If I had specs here I'd add them, but for you I'll do it live.

**Comment by jordanbyron** [comment]
Cut a new release for you @fastjames. Enjoy!
